apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-deployment
  namespace: snake-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-app
  template:
    metadata:
      labels:
        app: snake-app
    spec:
      containers:
      - name: snake-app
        image: docker.io/lopezleandro03/snake
        ports:
        - containerPort: 80