apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game
        image: lopezleandro03/snake-game
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snake-game
  namespace: apps
spec:
  selector:
    app: snake-game
  ports:
  - name: http
    port: 80
    targetPort: 80
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-game
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: copilotx-demo.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snake-game
            port:
              name: http