apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-app
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-app
  template:
    metadata:
      labels:
        app: snake-app
    spec:
      containers:
      - name: snake-game
        image: lopezleandro03/snake-game
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snake-service
  namespace: apps
spec:
  selector:
    app: snake-app
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-ingress
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: copilotx-demo.westeurope.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snake-service
                port:
                  name: http