apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-app
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-app
  template:
    metadata:
      labels:
        app: snake-app
    spec:
      containers:
      - name: snake-game
        image: lopezleandro03/snake-game
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: snake-service
  namespace: apps
spec:
  selector:
    app: snake-app
  ports:
    - name: http
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-snake
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  tls:
  - hosts:
    - copilotx-demo.westeurope.cloudapp.azure.com
    # secretName: {{Kubernetes Secret name with TLS/SSL Certificate}}
  rules:
  - host: copilotx-demo.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snake-service
            port:
              number: 80