apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game
        image: lopezleandro03/snake-game:latest
        ports:
        - containerPort: 80